name = str(input("Enter your name: "))
surname = str(input("Enter your surname:  "))
number = input("Enter your number(should start with +): ")
country = input("Enter your country: ")
city = input("Enter your city: ")
street = input("Enter your street: ")
house = input("Enter your house number: ")
flat= input("Enter your flat number: ")
index = input("Enter your index: ")

print(f"{name} {surname}")
print(f"{number}")
print(f"Вулиця {street} будинок {house} квартира {flat}, ")
print(f"{index}")
print(f"{country}")